<a href="https://colab.research.google.com/github/sandhyasrigajula-commits/python-assignments/blob/main/Pandas_Assignment_Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [242]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [243]:
# a =
a=pd.Series([100,200,300,400])

Print a, and data type

In [244]:
print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

Using indexing access the element 300 from the series a.

In [245]:
print(a[2])

300

What are the values of index for series a?

In [246]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [247]:
a.index=['c','a','b','d']
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [248]:
print(a.loc['d'])

400

Sort the values wrt to the index and print it

In [249]:
print(a.sort_index())

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [250]:
# b =
b=pd.Series([800,450,100],index=['e','f','g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [251]:
# a =
import pandas as pd
a = pd.concat([a,b])

In [252]:
#print a again after appending b into it

print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [253]:
# a =
sorta = a.sort_index(ascending=False)
print(sorta)
print(sorta.index)

g    100
f    450
e    800
d    400
c    100
b    300
a    200
dtype: int64
Index(['g', 'f', 'e', 'd', 'c', 'b', 'a'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [254]:
# df =

df = pd.DataFrame(a)
print(df)

     0
c  100
a  200
b  300
d  400
e  800
f  450
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [255]:
print(df.shape)

#(number of rows , number of columns)

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [256]:
# yep its same as the series.
print(df.index.equals(a.index))

True

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [257]:
print(df.head())
print(df.tail())

     0
c  100
a  200
b  300
d  400
e  800
     0
b  300
d  400
e  800
f  450
g  100

Rename the column of the dataframe as 'points'

In [258]:
df.columns =['points']
df

   points
c     100
a     200
b     300
d     400
e     800
f     450
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [259]:
#Create fruits array

# fruits =
import pandas as pd
import numpy as np
fruits = pd.Series(np.random.choice(['orange','mango','apple'],7))
print(fruits)

0     apple
1     apple
2     mango
3    orange
4     mango
5     mango
6    orange
dtype: object

In [260]:
#Create series fruits out of fruits array

# fruits =
fruits = np.random.choice(['orange','mango','apple'],7)
fruits= pd.Series(fruits)
print(fruits)

0     mango
1    orange
2     apple
3     apple
4    orange
5    orange
6     apple
dtype: object

Change the index of fruits to the index of dataframe df

In [261]:
fruits.index = df.index

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [262]:
df['fruits'] = fruits
print(df)

   points  fruits
c     100   mango
a     200  orange
b     300   apple
d     400   apple
e     800  orange
f     450  orange
g     100   apple

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [263]:
# d1 =
import pandas as pd
d1 = pd.DataFrame({'city': ['Chandigarh','Delhi','Kanpur','Chennai','Manali'] ,'Temperature':[15,20,22,26,-2]})

Print(d1)

In [264]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           20
2      Kanpur           22
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [265]:
print(d1.shape)

(5, 2)

Set city = d1['city']

In [266]:
city = d1['city']

print city <br>
What is the type of city.

In [267]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [268]:
# d2 =
import pandas as pd
d2 = pd.DataFrame({'city': ['Bengaluru','Coimbatore','Srirangam','Pondicherry'], 'Temperature': [24,35,36,39]})
print(d2)

          city  Temperature
0    Bengaluru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

print the shape of this dataframe

In [269]:
print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [270]:
# d3 =
import pandas as pd
d3 = pd.concat([d1,d2])
print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           20
2       Kanpur           22
3      Chennai           26
4       Manali           -2
0    Bengaluru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [271]:
d3[d3['Temperature'] <=20][['city']]

         city
0  Chandigarh
1       Delhi
4      Manali

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [272]:
d3[d3['Temperature'] >=35] [['city']]

          city
1   Coimbatore
2    Srirangam
3  Pondicherry

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [273]:
# write function here

# def is_ut(x):
import pandas as pd
def is_ut(x):
  ut = ['Chandigarh','Pondicherry','Delhi']
  return x in ut

#     # write code below

# d3['is_ut'] =
d3['is_ut'] = d3['city'].apply(is_ut)

In [274]:
# print d3
print(d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           20   True
2       Kanpur           22  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengaluru           24  False
1   Coimbatore           35  False
2    Srirangam           36  False
3  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [275]:
# write function here

import pandas as pd
def c_to_f(temp):
  return(temp *9/5) + 32

In [276]:
# check function c_to_f(10)

c_to_f(10)

50.0

In [277]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'

import pandas as pd
d3['temp_f'] = d3['Temperature'].apply(c_to_f)
print(d3)

          city  Temperature  is_ut  temp_f
0   Chandigarh           15   True    59.0
1        Delhi           20   True    68.0
2       Kanpur           22  False    71.6
3      Chennai           26  False    78.8
4       Manali           -2  False    28.4
0    Bengaluru           24  False    75.2
1   Coimbatore           35  False    95.0
2    Srirangam           36  False    96.8
3  Pondicherry           39   True   102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [278]:
import pandas as pd
d1 = pd.DataFrame({'city': ['Chandigarh','Delhi','Kanpur','Chennai','Manali'] ,'Temperature':[15,20,22,26,-2]})
ut =['Pondicherry','Chandigarh','Delhi']
ut_c = d1[d1['city'].isin(ut)]
print(ut_c)

         city  Temperature
0  Chandigarh           15
1       Delhi           20

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [279]:
print(d3[d3['temp_f'] > 90])

          city  Temperature  is_ut  temp_f
1   Coimbatore           35  False    95.0
2    Srirangam           36  False    96.8
3  Pondicherry           39   True   102.2

Select only the first three rows of the dataframe d1.

In [280]:
print(d1.head(3))

         city  Temperature
0  Chandigarh           15
1       Delhi           20
2      Kanpur           22

Select all the rows and last two columns in the dataframe.

In [281]:
print(d1.iloc[:,-2])

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object

## Groupby

In [282]:
# Create a dataframe using dictionary of your choice

# data =
data = pd.DataFrame({'Name':['sanju','siddhu','vaagdevi'],'Age':[25,30,1],'Marks':[90,70,80]})
print(data)

       Name  Age  Marks
0     sanju   25     90
1    siddhu   30     70
2  vaagdevi    1     80

In [283]:
# Use Groupby of single column with aggregate sum()

print(data.groupby(['Age']).sum())

         Name  Marks
Age
1    vaagdevi     80
25      sanju     90
30     siddhu     70

In [284]:
# Use Groupby of single column with aggregate count()

print(data.groupby('Age').count())

     Name  Marks
Age
1       1      1
25      1      1
30      1      1

In [285]:
# Use Groupby of single column with aggregate min() and max()

print(data.groupby('Marks').min())
print(data.groupby('Marks').max())

           Name  Age
Marks
70       siddhu   30
80     vaagdevi    1
90        sanju   25
           Name  Age
Marks
70       siddhu   30
80     vaagdevi    1
90        sanju   25

In [286]:
# Use Groupby of any 2 columns with aggregate mean()

print(data.groupby(['Name','Age']) ['Marks'].mean())

Name      Age
sanju     25     90.0
siddhu    30     70.0
vaagdevi  1      80.0
Name: Marks, dtype: float64

In [287]:
# Use Groupby of any 2 columns with aggregate min() and max()

print(data.groupby(['Name','Age'])['Marks'].min())
print(data.groupby(['Name','Age'])['Marks'].max())

Name      Age
sanju     25     90
siddhu    30     70
vaagdevi  1      80
Name: Marks, dtype: int64
Name      Age
sanju     25     90
siddhu    30     70
vaagdevi  1      80
Name: Marks, dtype: int64

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [288]:
# a =
import pandas as pd
a=pd.date_range(start = '2020-01-01', end = '2021-04-01')

print a

In [289]:

print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [290]:
print(len(a))

457

What is the type of a?

In [291]:
print(type(a))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>